FROM maven:3.8.4-openjdk-17

SHELL ["/bin/bash", "-c"]

ONBUILD WORKDIR /app

ONBUILD COPY . /app

ONBUILD RUN mvn dependency:resolve -f app/pom.xml \
            && mvn package -f app/pom.xml \
            && cp app/target/app.jar . \
            && rm -rf app/

CMD ["java", "-jar", "app.jar"]
