jenkins:
  systemMessage: "Welcome to the Whanos machine !"
  globalNodeProperties:
    - envVars:
        env:
          - key: PRIVATE_REGISTRY
            value: localhost:5000
  remotingSecurity:
    enabled: true
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          name: "Admin"
          password: "pass"
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Whanos administrator"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true

credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: git_ssh_key
              username: "${SSH_KEY_USERNAME}"
              description: "SSH key for Git."
              privateKeySource:
                directEntry:
                  privateKey: "${SSH_PRIVATE_KEY}"

security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false

jobs:
  - file: /jenkins/job_dsl.groovy

unclassified:
  gitSCM:
    globalConfigEmail: 'eloise.richard@epitech.eu'
    globalConfigName: 'Eloïse'